import React, { useEffect, useState } from 'react';
import { View, Text, FlatList, StyleSheet, TouchableOpacity, ActivityIndicator, Alert } from 'react-native';
import { Colors } from '@/constants/Colors';
import { COLORS } from '@/constants/cor';
import { useProductsControllerFindAll } from '@/api/generated';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useRouter } from 'expo-router';

  // Refetch data when the screen is focused
  import { useFocusEffect } from '@react-navigation/native';
const ProdutosListScreen = () => {
  const router = useRouter();
  const [isLoadingUserCheck, setIsLoadingUserCheck] = useState(true);
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    return () => setIsMounted(false);
  }, []);

  // Check if user is a logged-in gestor
  useEffect(() => {
    const checkUserRole = async () => {
      try {
        const token = await AsyncStorage.getItem('access_token');
        const userRole = await AsyncStorage.getItem('user_role');

        if (!token || userRole !== 'gestao') {
          if (isMounted) {
            setTimeout(() => {
              router.replace('/(login)/login');
            }, 0);
          }
        }
      } catch (error) {
        console.error('Failed to check user role from storage:', error);
        Alert.alert('Erro', 'Falha ao verificar permissões. Por favor, faça login novamente.');
        if (isMounted) {
          setTimeout(() => {
            router.replace('/(login)/login');
          }, 0);
        }
      } finally {
        setIsLoadingUserCheck(false);
      }
    };

    checkUserRole();
  }, [router, isMounted]);

  // Fetch all products using the hook generated by Orval
  const { 
    data: produtosResponse, 
    isLoading: isLoadingProdutos, 
    error: produtosError, 
    refetch 
  } = useProductsControllerFindAll({
    query: {
      queryKey: ['produtos'],
      enabled: !isLoadingUserCheck,
    }
  });

  const produtos = produtosResponse?.data || [];

  // Handle API errors
  useEffect(() => {
    if (produtosError) {
      console.error('Error fetching products:', produtosError);
      Alert.alert('Erro', 'Não foi possível carregar a lista de produtos.');
    }
  }, [produtosError]);


  useFocusEffect(
    React.useCallback(() => {
      if (!isLoadingUserCheck && isMounted) {
        refetch();
      }
    }, [isLoadingUserCheck, isMounted, refetch])
  );

  const handleNavigateToCreate = () => {
    if (isMounted) {
      router.push('/(home)/gestor/produtocreatescreen');
    }
  };

  const handleNavigateToDetail = (produtoId: string) => {
    if (isMounted) {
      router.push({ 
        pathname: '/(home)/gestor/produtodetailscreen', 
        params: { produtoId } 
      });
    }
  };

  if (isLoadingUserCheck || isLoadingProdutos) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" color={COLORS.primary} />
        <Text style={styles.loadingText}>Carregando produtos...</Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Gerenciar Produtos</Text>
        <TouchableOpacity 
          style={styles.createButton}
          onPress={handleNavigateToCreate}
        >
          <Text style={styles.createButtonText}>+ Novo Produto</Text>
        </TouchableOpacity>
      </View>

      {produtos.length > 0 ? (
        <FlatList
          data={produtos}
          keyExtractor={(item) => item.id.toString()}
          contentContainerStyle={styles.listContent}
          renderItem={({ item }) => (
            <TouchableOpacity
              style={styles.itemCard}
              onPress={() => handleNavigateToDetail(item.id)}
            >
              <View style={styles.itemHeader}>
                <Text style={styles.itemTitle}>{item.name}</Text>
                <Text style={styles.itemSubtitle}>Código: {item.code}</Text>
              </View>
              
              <View style={styles.itemDetails}>
                <Text style={styles.itemDetailText}>
                  <Text style={styles.itemDetailLabel}>Descrição: </Text>
                  {item.description || 'Não especificada'}
                </Text>
                <Text style={styles.itemDetailText}>
                  <Text style={styles.itemDetailLabel}>Preço: </Text>
                  {item.unitPrice ? `R$ ${item.unitPrice.toFixed(2)}` : 'Não especificado'}
                </Text>
              </View>
            </TouchableOpacity>
          )}
        />
      ) : (
        <View style={styles.emptyContainer}>
          <Text style={styles.emptyText}>Nenhum produto cadastrado.</Text>
          <TouchableOpacity
            style={styles.createButton}
            onPress={handleNavigateToCreate}
          >
            <Text style={styles.createButtonText}>Criar Primeiro Produto</Text>
          </TouchableOpacity>
        </View>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: COLORS.text?.secondary || '#666',
  },
  header: {
    backgroundColor: COLORS.primary,
    padding: 20,
    paddingTop: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.white,
  },
  createButton: {
    backgroundColor: COLORS.accent || '#FFC107',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  createButtonText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 14,
  },
  listContent: {
    padding: 16,
  },
  itemCard: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  itemHeader: {
    marginBottom: 12,
  },
  itemTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.text?.primary || '#333',
  },
  itemSubtitle: {
    fontSize: 14,
    color: COLORS.text?.secondary || '#666',
    marginTop: 4,
  },
  itemDetails: {
    marginTop: 8,
  },
  itemDetailText: {
    fontSize: 14,
    color: COLORS.text?.secondary || '#666',
    marginBottom: 4,
  },
  itemDetailLabel: {
    fontWeight: 'bold',
    color: COLORS.text?.primary || '#333',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    color: COLORS.text?.secondary || '#666',
    textAlign: 'center',
    marginBottom: 20,
  },
});

export default ProdutosListScreen;