import React, { useEffect, useState, useCallback } from 'react';
import { View, Text, FlatList, StyleSheet, TouchableOpacity, ActivityIndicator, Alert, RefreshControl } from 'react-native';
import { Colors } from '@/constants/Colors';
import { COLORS } from '@/constants/cor';
import { useSectorsControllerFindAll } from '@/api/generated';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useFocusEffect, useRouter } from 'expo-router';

const SetoresListScreen = () => {
  const router = useRouter();
  const [isLoadingUserCheck, setIsLoadingUserCheck] = useState(true);
  const [isMounted, setIsMounted] = useState(false);
  const [refreshing, setRefreshing] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    return () => setIsMounted(false);
  }, []);

  // Check if user is a logged-in gestor
  useEffect(() => {
    const checkUserRole = async () => {
      try {
        const token = await AsyncStorage.getItem('access_token');
        const userRole = await AsyncStorage.getItem('user_role');

        console.log('Token:', token);
        console.log('User Role:', userRole);

        if (!token || userRole !== 'gestao') {
          if (isMounted) {
            setTimeout(() => {
              router.replace('/(login)/login');
            }, 0);
          }
        }
      } catch (error) {
        console.error('Failed to check user role from storage:', error);
        Alert.alert('Erro', 'Falha ao verificar permissões. Por favor, faça login novamente.');
        if (isMounted) {
          setTimeout(() => {
            router.replace('/(login)/login');
          }, 0);
        }
      } finally {
        setIsLoadingUserCheck(false);
      }
    };

    checkUserRole();
  }, [router, isMounted]);

  // Fetch all sectors using the hook generated by Orval
  const { 
    data: setoresResponse, 
    isLoading: isLoadingSetores, 
    error: setoresError, 
    refetch 
  } = useSectorsControllerFindAll({
    query: {
      enabled: !isLoadingUserCheck,
      onSuccess: (data) => {
        console.log('Dados de setores recebidos com sucesso:', data);
        setRefreshing(false);
      },
      onError: (error) => {
        console.error('Erro ao buscar setores:', error);
        setRefreshing(false);
      }
    }
  });

  // Handle different response structures
  const setores = Array.isArray(setoresResponse) 
    ? setoresResponse 
    : setoresResponse?.data 
    ? setoresResponse.data 
    : [];

  // Handle API errors
  useEffect(() => {
    if (setoresError) {
      console.error('Detalhes do erro:', {
        message: setoresError.message,
        response: setoresError.response?.data,
        status: setoresError.response?.status
      });
      
      Alert.alert(
        'Erro', 
        setoresError.response?.data?.message || 
        'Não foi possível carregar a lista de setores.'
      );
    }
  }, [setoresError]);

  // Refetch data when the screen is focused
  useFocusEffect(
    useCallback(() => {
      if (!isLoadingUserCheck && isMounted) {
        refetch();
      }
    }, [isLoadingUserCheck, refetch, isMounted])
  );

  const onRefresh = useCallback(() => {
    setRefreshing(true);
    refetch();
  }, [refetch]);

  const handleNavigateToCreate = () => {
    if (isMounted) {
      router.push('/(home)/gestor/setorcreatescreen');
    }
  };

  const handleNavigateToDetail = (setorId: string) => {
    if (isMounted) {
      router.push({ 
        pathname: '/(home)/gestor/setordetailscreen', 
        params: { setorId } 
      });
    }
  };

  // Debug logs
  console.log('Estado atual:', {
    isLoadingUserCheck,
    isLoadingSetores,
    setoresError,
    setoresResponse,
    setores
  });

  if (isLoadingUserCheck || isLoadingSetores) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" color={COLORS.primary} />
        <Text style={styles.loadingText}>Carregando setores...</Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Gerenciar Setores</Text>
        <TouchableOpacity 
          style={styles.createButton}
          onPress={handleNavigateToCreate}
        >
          <Text style={styles.createButtonText}>+ Novo Setor</Text>
        </TouchableOpacity>
      </View>

      {setores.length > 0 ? (
        <FlatList
          data={setores}
          keyExtractor={(item) => item.id.toString()}
          contentContainerStyle={styles.listContent}
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={onRefresh}
              colors={[COLORS.primary]}
            />
          }
          renderItem={({ item }) => (
            <TouchableOpacity
              style={styles.itemCard}
              onPress={() => handleNavigateToDetail(item.id)}
            >
              <View style={styles.itemHeader}>
                <Text style={styles.itemTitle}>{item.name}</Text>
                <Text style={styles.itemSubtitle}>Código: {item.code}</Text>
              </View>
              
              <View style={styles.itemDetails}>
                <Text style={styles.itemDetailText}>
                  <Text style={styles.itemDetailLabel}>Descrição: </Text>
                  {item.description || 'Não especificada'}
                </Text>
              </View>
            </TouchableOpacity>
          )}
        />
      ) : (
        <View style={styles.emptyContainer}>
          <Text style={styles.emptyText}>Nenhum setor cadastrado.</Text>
          <TouchableOpacity
            style={styles.createButton}
            onPress={handleNavigateToCreate}
          >
            <Text style={styles.createButtonText}>Criar Primeiro Setor</Text>
          </TouchableOpacity>
        </View>
      )}
    </View>
  );
};

// Estilos permanecem os mesmos do seu código original
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: COLORS.text?.secondary || '#666',
  },
  header: {
    backgroundColor: COLORS.primary,
    padding: 20,
    paddingTop: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.white,
  },
  createButton: {
    backgroundColor: COLORS.accent || '#FFC107',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  createButtonText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 14,
  },
  listContent: {
    padding: 16,
  },
  itemCard: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  itemHeader: {
    marginBottom: 12,
  },
  itemTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.text?.primary || '#333',
  },
  itemSubtitle: {
    fontSize: 14,
    color: COLORS.text?.secondary || '#666',
    marginTop: 4,
  },
  itemDetails: {
    marginTop: 8,
  },
  itemDetailText: {
    fontSize: 14,
    color: COLORS.text?.secondary || '#666',
    marginBottom: 4,
  },
  itemDetailLabel: {
    fontWeight: 'bold',
    color: COLORS.text?.primary || '#333',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    color: COLORS.text?.secondary || '#666',
    textAlign: 'center',
    marginBottom: 20,
  },
});

export default SetoresListScreen;