/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */
import type { CreateAuthDtoRole } from './createAuthDtoRole';

export interface CreateAuthDto {
  /** Código do usuário */
  code: string;
  /** Senha do usuário */
  password: string;
}
